# Where the recordings will be stored
base_path: ./recordings
save_format: 'bmp'

# Add your sources below
sources:
#    red:
#        type: basler
#        serial: xxxxxxxx
#        color: e03228
#    green:
#        type: basler
#        serial: xxxxxxxx
#        color: 15ab79
#    yellow:
#        type: basler
#        serial: xxxxxxxx
#        color: fff139
#    blue:
#        type: basler
#        serial: xxxxxxxx
#        color: 435fc4
#    white:
#        type: basler
#        serial: xxxxxxxx
#        color: fdfdfd
    purple:
        type: basler
        color: F47FFD
        virtual: true
    othervirt:
        type: basler
        color: fd421c
        virtual: true
    vid_0:
        type: file
        path: /path/to/video_0
        color: fff139
    vid_1:
        type: file
        path: /path/to/video_1
        color: 435fc4
    vid_2:
        type: file
        path: /path/to/video_2
        color: fdfdfd