# Where the recordings will be stored
base_path: /home/oakleigh/Documents/trigger_pics
save_format: 'mp4'
save_quality: 100    # 0 - 100%
gpu: true

# Add your sources below
sources:
    left:         # Choose a name
        type: basler
        serial: 40485344
        color: da141d
    right:
        type: basler
        serial: 40485346
        color: 7a9c21
    wide:
        type: basler
        serial: 40625804
        color: f3d586
