# Where the recordings will be stored
base_path: D:/
save_format: 'uu'
save_quality: 80    # 0 - 100%

# Add your sources below
sources:
    red:
        type: basler
        serial: xxxxxx
        color: e03228
    green:
        type: basler
        serial: xxxxxx
        color: 15ab79
    yellow:
        type: basler
        serial: xxxxxx
        color: fff139
    blue:
        type: basler
        serial: xxxxxx
        color: 435fc4
    white:
        type: basler
        serial: xxxxxx
        color: fdfdfd
