# ----------------------------------
#  Mokap Example Configuration File
# ----------------------------------

# --- Global Acquisition Settings ---
base_path: D:/MokapTests    # where the recordings will be stored
hardware_trigger: true      # whether to use an external hardware trigger
framerate: 60               # in frames per seconds (Hz)
exposure: 15000             # in milliseconds
trigger_line: 4             # which GPIO line is used as an input (to listen to the hardware trigger)
gain: 1.0
pixel_format: Mono8         # or Mono10, BGR8, BayerRG8, ...
binning: 1                  # or 2, 3, 4
binning_mode: average       # or sum
black_level: 1.0
gamma: 1.0
roi: [0, 0, 1440, 1080]     # ROI can be [x offset, y offset, width, height] or [width, height] (automatically centered)

# --- Global Saving & Encoding Settings ---
save_format: mp4          # or 'png', 'jpg', 'bmp', 'tiff'
save_quality: 90          # 0-100 scale (only for images, ignored in video encoding)
frame_buffer_size: 200    # max number of frames to buffer in RAM (per camera)

# --- Hardware trigger parameters ---
# You can use a Raspberry Pi
trigger:
  type: raspberry
  pin: 18           # The GPIO pin you connect your cameras to. Pin 18 is recommended.

## or an Arduino
#trigger:
#  type: arduino
#  port: COM5        # 'COMX' on Windows, '/dev/ttyUSBX' on Linux, '/dev/cu.usbserial-XXXX' on macOS
#  pin: 11           # The GPIO pin you connect your cameras to. Usually 3 or 11 on Arduino
#  baudrate: 115200  # Optional. If you use one of the two firmwares provided with Mokap, you should not change this

## or a USB-to-TTL adapter (this is less accurate though)
#trigger:
#  type: ftdi
#  port: COM3         # 'COMX' on Windows, '/dev/ttyUSBX' on Linux, '/dev/cu.usbserial-XXXX' on macOS
#  pin: RTS           # Optional, can be 'RTS' or 'DTR'
#  baudrate: 9600     # Optional. Should not matter too much

## or use one of the cameras to control the others
#trigger:
#  type: camera
#  name: my-first-camera     # use the friendly name from 'sources'
#  output_line: 2            # The GPIO line to use for output

# --- Video encoding parameters ---
ffmpeg:
  path: 'ffmpeg'
  gpu: true

  params:
    # --- CPU Profiles ---
    # H.265
    cpu_h265: >-
      -c:v libx265 -preset superfast -tune zerolatency -crf 20 -x265-params "vbv-maxrate=60000k:vbv-bufsize=120000k:keyint=100:min-keyint=100"
    # H.264
    cpu_h264: >-
      -c:v libx264 -preset superfast -tune zerolatency -crf 21

    # --- NVIDIA Profiles ---
    # H.265
    gpu_nvenc_h265: >-
      -c:v hevc_nvenc -preset slow -tune ll -rc constqp -qp 19 -g 100 -bf 0
    # H.264
    gpu_nvenc_h264: >-
      -c:v h264_nvenc -preset slow -tune ll -rc constqp -qp 20 -g 100 -bf 0

    # --- AMD profile (Windows) ---
    gpu_amf: >-
      -c:v hevc_amf -preset quality -low_latency 1 -rc vbr_hq -quality 20 -g 100 -bf 0

    # --- AMD profile (Linux) ---
    gpu_vaapi: >-
      -vaapi_device /dev/dri/renderD128 -c:v hevc_vaapi -qp 21 -g 100 -bf 0

    # --- Apple profiles ---
    gpu_videotoolbox: >-
      -c:v hevc_videotoolbox -realtime true -q:v 80 -allow_sw 1 -g 100

    # --- Intel QSV profiles (for Intel Arc GPUs, or Intel CPUs with QSV) ---
    gpu_arc_av1: >-
      -c:v av1_qsv -preset veryfast -global_quality 23 -low_power 0 -g 100 -bf 0
    gpu_arc_hevc: >-
      -c:v hevc_qsv -preset veryfast -global_quality 21 -low_power 0 -g 100 -bf 0

# --- Camera-Specific Definitions ---

# This is where you add your cameras
sources:
  my-first-camera: # This is your defined, friendly name for this camera :)
    vendor: basler
    serial: xxxxxxxx  # you can specify the serial number to make sure it gets the right name, colour etc
    color: da141d
#    # Camera-specific settings can override globals
#    exposure: 9000
#    gain: 2.0
#    gamma: 1.5
#    pixel_format: Mono8
#    blacks: 1.0
#    binning: 1
#    save_format: jpg
#    save_quality: 90   # you can set per-camera writer settings

  some-other-camera:
    vendor: flir
    color: 7a9c21

  # You can also use your laptop's internal camera (or any USB webcam)
  # Features are limited of course, but it is useful for debugging
  laptop-camera:
    vendor: webcam
    color: f3d586