name: mokap
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip=23.3.1
  - numpy=1.26.0
  - pillow=10.0.1
  - python-dotenv=0.21.0
  - paramiko=2.8.1
  - scipy
  - opencv
  - pip:
      - pypylon==2.3.0
      - screeninfo==0.8.1