name: mokap
channels:
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - numpy=1.26.0
  - pillow=10.0.1
  - zarr=2.13.3
  - python-dotenv=0.21.0
  - paramiko=2.8.1
  - scipy=1.11.3
  - matplotlib=3.7.2
  - blosc=1.21.3
  - pip:
      - pypylon==2.3.0
      - screeninfo==0.8.1